### PR TITLE
Changes for Jetstream on Kubespray v2.13.1

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by rptaylor** [comment]
@zonca nice blog post. If you are thinking of pushing enhancements to upstream kubespray, regarding the security groups for master nodes, take a look at the TF variable worker_allowed_ports ; it would make sense to consolidate all sec group rules into a similar structure for masters (e.g. master_allowed_ports) instead of creating port-specific ones (there is also already master_allowed_remote_ips for API access). 

Regarding certificate validity for a floating IP address, you can use the Ansible variable supplementary_addresses_in_ssl_keys to fix this, which will add a SAN to the cert (certs will need to be regenerated though), see https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ha-mode.md  for some documentation.

**Comment by zonca** [comment]
thanks @rptaylor 
`supplementary_addresses_in_ssl_keys` is really helpful, that will simplify the tutorial and improve security!

**Comment by zonca** [comment]
@rptaylor, good news is someone implemented the master_allowed_ports option https://github.com/kubernetes-sigs/kubespray/pull/7196

**Comment by zonca** [comment]
thanks @rptaylor I have the new version of the deployment, using `supplementary_addresses_in_ssl_keys`

**Comment by zonca** [comment]
https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/issues/44

**Pull request closed without merging**
